name: upload_files_widgets
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.3.2
  image_picker: ^1.1.1
  tus_client_dart: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
